---
title: "Instructions for generating a cruise report from the winter survey"
author: "Johanna Fall"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Create a project and folder structure

1. Create a new R Studio project.

2. Download the cruise report script *Report_Winter_Survey.Rmd* from https://github.com/jofall/Cruisenotebook and place in project directory (or fork/download the entire repository).

3. The script requires a specific folder structure for storing the cruise data. Create these folders in the project directory:
   + Data
      + Acoustic
         + Integrated
         + Channels
      + Biotic
      + CTD
      + Track
      + Definitions
      + GeoData
   
For acoustic, biotic and track data, it is also possible to replace the folder structure with paths directly to the location of data on the server on board. This way, the files in the script with be updated automatically when you knit the file. However, CTD data cannot be read directly from the server location with this version of the script (as there are several different types of .cnv-files and the current code looks for files with this extension).

4. Download the HI logo from https://hinnsiden.no/tema/profiltorg/LOGO/HI%20logo%20farger%20engelsk.jpg and place in project directory (optional, but see information below on how to avoid an error if you do not include the logo).

## Gather data

Collect the following cruise data from the server on board:

1. Acoustic data: *ListUserFile03.txt* and *ListUserFile16.txt*. If these reports have not been created, export them from LSSS.
   + Example path to acoustic reports on Johan Hjort: //nas1-jhjort/CRUISE_DATA_*YEAR*/  
   *cruise_name*/ACOUSTIC/LSSS/REPORTS/
   + Place in "Acoustic" folder.

2. Trawl data: The *.xml* file exported from Sea2Data. 
   + Example path from Johan Hjort: //nas1-jhjort/CRUISE_DATA_*YEAR*/*cruise_name*/  
   BIOLOGY/CATCH_MEASUREMENTS/BIOTIC/
   + Place in "Biotic" folder.

3. CTD data: *ctdsort.cnv*-files (one for each CTD cast).
   + Example path from Johan Hjort: //nas1-jhjort/CRUISE_DATA_*YEAR*/*cruise_name*/  
   PHYSICS/CTD/CTD_DATA/
   + Place in "CTD" folder.

4. Definitions: These is a file used for reading the biotic xlm-data. Download it from https://github.com/jofall/Cruisenotebook and place in folder "Definitions".

5. Map data: depth contours for plotting. Download the file *ETOPO1_nm4.csv* from the github repository and place in folder "GeoData".

6. Cruise track data: .csv-files (one for each day).
   + Example path from Johan Hjort:
   //nas1-jhjort/CRUISE_DATA_*YEAR*/*cruise_name*/  
   CRUISE_LOG/TRACK/
   + Place in "Track" folder.

NB! It is important not to place other files in these folders, as the code is based on loading files with specific file extensions.

## Change or check the following in the script to adapt the report to specific survey areas and species in the catch

Line numbers refer to the file *Report_Winter_Survey.Rmd*

1. Remove line 3 if you do not wish to have the HI logo.

2. Change title and author.

3. Check the r packages specified in the second r code chunk (lines 27-29), and install any packages you do not have on your computer.

4. Lines 44-46: specify the extent of your survey area and the depth contours you would like to show in map plots.

### Trawl data

5. Load packages by running lines 27-29 (without knitting the whole document!), then run lines 55-76. Run unique(dataset$`Station type`) and check that the gear definitions on lines 80-87 correspond to those used in your cruise. If not, change the definitions.

6. Check if you are using any other trawls than those specified at lines 496-497, if so add them/modify. Change also the gears at line 510-511 if necessary.

7. Lines 619-910 contain code for plotting catches of different species on a map, by gear type. For each species, two sets of plots are produced - one showing catch rates in biomass/nmi and one showing numbers/nmi. Adjust this code to match the species in your area by changing the "species <-" argument in each code chunk, and deleting/copying code chunks as necessary. The figure size can be adjusted using the "fig.width" and "fig.height" arguments at the beginning of each code chunk. In this example, this has been done for polar cod, blue whiting, and redfish, which were caught in fewer gears than the other species.

8. Lines 926-927: specify the species that you wish to plot length distributions, length-weight relationships, and length-age relationships for. Here they are divided into larger (demersal) and smaller (pelagic) species. Note that age data will not be available early in the survey, and will later only be available for species whose otholits are read on board.

9. Line 1021: This inline code summarises the total distance of scrutinized acoustic transects, accounting for the possibility of a reset in the log values, i.e., that the log reaches 10000 and then starts over from 1. No change necessary.

10. Line 1023: In this section it is possible to add screenshots from LSSS (or other images) in case you find particularly interesting or unusual echograms. The screenshot must be placed in the project directory, and the filename inserted within the brackets on line 1025. Remove the "<" sign at the beginning of each paragraph. The figure width can be adjusted within the curly brackets. Remove line 1023-1027 in case you have no screenshots to add.

### Acoustic data

11. Line 1035: For acoustic plots, the maximum bubble size can be adjusted here.

12. Line 1038: Change year manually in case you are using this script to plot data from a past year, or use code on line 1039.

13. Line 1040: This script selects data from the 38 kHz frequency, which is what is normally exported from LSSS. Change here if you are looking at other frequencies.

14. Line 1053: If you want other names for the acoustic categories than the Norwegian output from LSSS, specify labels here. "Comment out" or delete lines 1053-1057 & 1093-1095 if you don't want to change the names.

15. Line 1062: Check name of survey and vessel.

16. Line 1084/1104: Specify names of pelagic/demersal acoustic categories that you want to plot on a map.

### CTD

17. Line 1370: Choose the maximum depth for plots of density and irradiance.

---